export const FOOD_ES = {
  "Apples":"Manzanas","Avocado":"Aguacate","Bananas":"Pl\u00e1tanos","Bell Pepper":"Pimiento",
  "Blueberries":"Ar\u00e1ndanos","Broccoli":"Br\u00f3coli","Carrots":"Zanahorias","Celery":"Apio",
  "Cherries":"Cerezas","Corn":"Ma\u00edz","Cucumber":"Pepino","Garlic":"Ajo","Ginger":"Jengibre",
  "Grapes":"Uvas","Green Beans":"Ejotes","Green Onions":"Cebollitas","Kale":"Col Rizada",
  "Lemons":"Limones","Lettuce":"Lechuga","Limes":"Limas","Mango":"Mango","Mushrooms":"Champi\u00f1ones",
  "Onions":"Cebollas","Oranges":"Naranjas","Peaches":"Duraznos","Pears":"Peras","Pineapple":"Pi\u00f1a",
  "Potatoes":"Papas","Raspberries":"Frambuesas","Spinach":"Espinacas","Strawberries":"Fresas",
  "Sweet Potatoes":"Camotes","Tomatoes":"Tomates","Watermelon":"Sand\u00eda","Zucchini":"Calabac\u00edn",
  "Asparagus":"Esp\u00e1rragos","Cauliflower":"Coliflor","Eggplant":"Berenjena","Peas":"Ch\u00edcharos",
  "Cabbage":"Repollo","Jalape\u00f1o":"Jalape\u00f1o","Cilantro":"Cilantro","Parsley":"Perejil",
  "Basil":"Albahaca","Mint":"Menta","Radishes":"R\u00e1banos",
  "Milk":"Leche","Eggs":"Huevos","Butter":"Mantequilla","Cheddar Cheese":"Queso Cheddar",
  "Mozzarella":"Mozzarella","Parmesan":"Parmesano","Cream Cheese":"Queso Crema","Yogurt":"Yogur",
  "Greek Yogurt":"Yogur Griego","Sour Cream":"Crema Agria","Heavy Cream":"Crema Espesa",
  "Cottage Cheese":"Reques\u00f3n","Almond Milk":"Leche de Almendra","Oat Milk":"Leche de Avena",
  "Chicken Breast":"Pechuga de Pollo","Ground Beef":"Carne Molida","Bacon":"Tocino",
  "Salmon":"Salm\u00f3n","Shrimp":"Camarones","Pork Chops":"Chuletas de Cerdo","Steak":"Bistec",
  "Ground Turkey":"Pavo Molido","Ham":"Jam\u00f3n","Sausage":"Salchicha","Tilapia":"Tilapia",
  "Tuna":"At\u00fan","Turkey Breast":"Pechuga de Pavo","Hot Dogs":"Hot Dogs","Lamb":"Cordero",
  "Cod":"Bacalao","Crab":"Cangrejo",
  "Rice":"Arroz","Pasta":"Pasta","Bread":"Pan","Flour":"Harina","Sugar":"Az\u00facar",
  "Olive Oil":"Aceite de Oliva","Peanut Butter":"Crema de Cacahuate","Canned Beans":"Frijoles Enlatados",
  "Canned Tomatoes":"Tomates Enlatados","Cereal":"Cereal","Oats":"Avena","Honey":"Miel",
  "Soy Sauce":"Salsa de Soya","Vinegar":"Vinagre","Ketchup":"Ketchup","Mustard":"Mostaza",
  "Mayonnaise":"Mayonesa","Hot Sauce":"Salsa Picante","Salsa":"Salsa","Jam":"Mermelada",
  "Maple Syrup":"Miel de Maple","Chips":"Papas Fritas","Crackers":"Galletas Saladas",
  "Granola":"Granola","Nuts":"Nueces","Canned Soup":"Sopa Enlatada","Tortillas":"Tortillas",
  "Baked Beans":"Frijoles Horneados","Coconut Milk":"Leche de Coco","Ramen":"Ramen",
  "Coffee":"Caf\u00e9","Tea":"T\u00e9","Orange Juice":"Jugo de Naranja","Apple Juice":"Jugo de Manzana",
  "Frozen Pizza":"Pizza Congelada","Frozen Vegetables":"Verduras Congeladas",
  "Ice Cream":"Helado","Frozen Fruit":"Fruta Congelada","Frozen Chicken":"Pollo Congelado",
  "Pizza":"Pizza","Leftover Soup":"Sopa Sobrante","Leftover Rice":"Arroz Sobrante",
  "Cooked Chicken":"Pollo Cocido","Cooked Pasta":"Pasta Cocida",
  "Tofu":"Tofu","Hummus":"Hummus","Tortilla Chips":"Totopos","Popcorn":"Palomitas",
  "Chocolate":"Chocolate","Avocado Oil":"Aceite de Aguacate","Sesame Oil":"Aceite de S\u00e9samo",
  "Balsamic Vinegar":"Vinagre Bals\u00e1mico","Dijon Mustard":"Mostaza Dijon",
  "Ranch Dressing":"Aderezo Ranch","BBQ Sauce":"Salsa BBQ","Teriyaki Sauce":"Salsa Teriyaki",
  "Sriracha":"Sriracha","Worcestershire":"Salsa Inglesa","Pickles":"Pepinillos",
  "Olives":"Aceitunas","Capers":"Alcaparras","Dried Pasta":"Pasta Seca",
  "Quinoa":"Quinoa","Lentils":"Lentejas","Black Beans":"Frijoles Negros",
  "Chickpeas":"Garbanzos","Brown Rice":"Arroz Integral","Couscous":"Cusc\u00fas",
  "Baking Powder":"Polvo para Hornear","Baking Soda":"Bicarbonato",
  "Vanilla Extract":"Extracto de Vainilla","Cinnamon":"Canela","Cumin":"Comino",
  "Paprika":"Piment\u00f3n","Black Pepper":"Pimienta Negra","Salt":"Sal",
  "Oregano":"Or\u00e9gano","Thyme":"Tomillo","Rosemary":"Romero",
  "Bay Leaves":"Hojas de Laurel","Chili Powder":"Chile en Polvo",
  "Turmeric":"C\u00farcuma","Garlic Powder":"Ajo en Polvo",
  "Onion Powder":"Cebolla en Polvo","Italian Seasoning":"Sazonador Italiano",
  "Cornstarch":"Maicena","Breadcrumbs":"Pan Molido","Tomato Paste":"Pasta de Tomate",
  "Coconut Oil":"Aceite de Coco","Vegetable Oil":"Aceite Vegetal","Walnuts":"Nueces",
  "Almonds":"Almendras","Pecans":"Pecanas","Cashews":"Anacardos",
  "Peanuts":"Cacahuates","Raisins":"Pasas","Dried Cranberries":"Ar\u00e1ndanos Secos"
};

export const FOOD_DB = [
  // === PRODUCE ===
  { name: "Apples", category: "Produce", location: "Fridge", daysSealed: 28, daysAfterOpening: null },
  { name: "Asparagus", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Avocado", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: 2 },
  { name: "Bananas", category: "Produce", location: "Pantry", daysSealed: 7, daysAfterOpening: null },
  { name: "Basil", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Beets", category: "Produce", location: "Fridge", daysSealed: 14, daysAfterOpening: null },
  { name: "Bell Peppers", category: "Produce", location: "Fridge", daysSealed: 10, daysAfterOpening: 5 },
  { name: "Berries", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Blackberries", category: "Produce", location: "Fridge", daysSealed: 4, daysAfterOpening: null },
  { name: "Blueberries", category: "Produce", location: "Fridge", daysSealed: 10, daysAfterOpening: null },
  { name: "Bok Choy", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Broccoli", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Brussels Sprouts", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Butternut Squash", category: "Produce", location: "Pantry", daysSealed: 30, daysAfterOpening: 5 },
  { name: "Cabbage", category: "Produce", location: "Fridge", daysSealed: 14, daysAfterOpening: 5 },
  { name: "Cantaloupe", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Carrots", category: "Produce", location: "Fridge", daysSealed: 21, daysAfterOpening: 7 },
  { name: "Cauliflower", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Celery", category: "Produce", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Cherries", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Cilantro", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Corn", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Cranberries", category: "Produce", location: "Fridge", daysSealed: 21, daysAfterOpening: null },
  { name: "Cucumber", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Eggplant", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Garlic", category: "Produce", location: "Pantry", daysSealed: 60, daysAfterOpening: 10 },
  { name: "Ginger", category: "Produce", location: "Fridge", daysSealed: 21, daysAfterOpening: 7 },
  { name: "Grapes", category: "Produce", location: "Fridge", daysSealed: 10, daysAfterOpening: null },
  { name: "Green Beans", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Green Onions", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Honeydew", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Jalapenos", category: "Produce", location: "Fridge", daysSealed: 14, daysAfterOpening: null },
  { name: "Kale", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Leeks", category: "Produce", location: "Fridge", daysSealed: 10, daysAfterOpening: null },
  { name: "Lemons", category: "Produce", location: "Fridge", daysSealed: 21, daysAfterOpening: 5 },
  { name: "Lettuce", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Limes", category: "Produce", location: "Fridge", daysSealed: 21, daysAfterOpening: 5 },
  { name: "Mangoes", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Mushrooms", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 4 },
  { name: "Nectarines", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Onions", category: "Produce", location: "Pantry", daysSealed: 30, daysAfterOpening: 7 },
  { name: "Oranges", category: "Produce", location: "Fridge", daysSealed: 21, daysAfterOpening: null },
  { name: "Parsley", category: "Produce", location: "Fridge", daysSealed: 10, daysAfterOpening: null },
  { name: "Peaches", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Pears", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },
  { name: "Peas", category: "Produce", location: "Freezer", daysSealed: 240, daysAfterOpening: null },
  { name: "Pineapple", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: 3 },
  { name: "Plums", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Pomegranate", category: "Produce", location: "Fridge", daysSealed: 30, daysAfterOpening: 5 },
  { name: "Potatoes", category: "Produce", location: "Pantry", daysSealed: 28, daysAfterOpening: null },
  { name: "Radishes", category: "Produce", location: "Fridge", daysSealed: 14, daysAfterOpening: null },
  { name: "Raspberries", category: "Produce", location: "Fridge", daysSealed: 3, daysAfterOpening: null },
  { name: "Romaine Lettuce", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Rosemary", category: "Produce", location: "Fridge", daysSealed: 14, daysAfterOpening: null },
  { name: "Shallots", category: "Produce", location: "Pantry", daysSealed: 30, daysAfterOpening: 7 },
  { name: "Snow Peas", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Spinach", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Strawberries", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Sweet Potatoes", category: "Produce", location: "Pantry", daysSealed: 28, daysAfterOpening: null },
  { name: "Swiss Chard", category: "Produce", location: "Fridge", daysSealed: 5, daysAfterOpening: null },
  { name: "Thyme", category: "Produce", location: "Fridge", daysSealed: 14, daysAfterOpening: null },
  { name: "Tomatoes", category: "Produce", location: "Pantry", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Turnips", category: "Produce", location: "Fridge", daysSealed: 14, daysAfterOpening: null },
  { name: "Watermelon", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Zucchini", category: "Produce", location: "Fridge", daysSealed: 7, daysAfterOpening: null },

  // === DAIRY ===
  { name: "Butter", category: "Dairy", location: "Fridge", daysSealed: 90, daysAfterOpening: 30 },
  { name: "Buttermilk", category: "Dairy", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Cheddar Cheese", category: "Dairy", location: "Fridge", daysSealed: 42, daysAfterOpening: 21 },
  { name: "Colby Jack", category: "Dairy", location: "Fridge", daysSealed: 42, daysAfterOpening: 21 },
  { name: "Cottage Cheese", category: "Dairy", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Cream", category: "Dairy", location: "Fridge", daysSealed: 21, daysAfterOpening: 7 },
  { name: "Cream Cheese", category: "Dairy", location: "Fridge", daysSealed: 30, daysAfterOpening: 14 },
  { name: "Eggs", category: "Dairy", location: "Fridge", daysSealed: 35, daysAfterOpening: null },
  { name: "Feta Cheese", category: "Dairy", location: "Fridge", daysSealed: 42, daysAfterOpening: 7 },
  { name: "Goat Cheese", category: "Dairy", location: "Fridge", daysSealed: 21, daysAfterOpening: 7 },
  { name: "Greek Yogurt", category: "Dairy", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Gruyere", category: "Dairy", location: "Fridge", daysSealed: 42, daysAfterOpening: 21 },
  { name: "Half and Half", category: "Dairy", location: "Fridge", daysSealed: 14, daysAfterOpening: 5 },
  { name: "Heavy Cream", category: "Dairy", location: "Fridge", daysSealed: 21, daysAfterOpening: 7 },
  { name: "Mascarpone", category: "Dairy", location: "Fridge", daysSealed: 14, daysAfterOpening: 5 },
  { name: "Milk", category: "Dairy", location: "Fridge", daysSealed: 10, daysAfterOpening: 7 },
  { name: "Mozzarella", category: "Dairy", location: "Fridge", daysSealed: 21, daysAfterOpening: 7 },
  { name: "Oat Milk", category: "Dairy", location: "Fridge", daysSealed: 10, daysAfterOpening: 7 },
  { name: "Parmesan", category: "Dairy", location: "Fridge", daysSealed: 180, daysAfterOpening: 42 },
  { name: "Pepper Jack", category: "Dairy", location: "Fridge", daysSealed: 42, daysAfterOpening: 21 },
  { name: "Provolone", category: "Dairy", location: "Fridge", daysSealed: 42, daysAfterOpening: 21 },
  { name: "Ricotta", category: "Dairy", location: "Fridge", daysSealed: 14, daysAfterOpening: 5 },
  { name: "Sour Cream", category: "Dairy", location: "Fridge", daysSealed: 21, daysAfterOpening: 14 },
  { name: "Swiss Cheese", category: "Dairy", location: "Fridge", daysSealed: 42, daysAfterOpening: 21 },
  { name: "Whipping Cream", category: "Dairy", location: "Fridge", daysSealed: 21, daysAfterOpening: 5 },
  { name: "Yogurt", category: "Dairy", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },

  // === MEAT & SEAFOOD ===
  { name: "Bacon", category: "Meat", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Bratwurst", category: "Meat", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Chicken Breast", category: "Meat", location: "Freezer", daysSealed: 270, daysAfterOpening: 2 },
  { name: "Chicken Thighs", category: "Meat", location: "Freezer", daysSealed: 270, daysAfterOpening: 2 },
  { name: "Chicken Wings", category: "Meat", location: "Freezer", daysSealed: 270, daysAfterOpening: 2 },
  { name: "Chorizo", category: "Meat", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Cod", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 2 },
  { name: "Crab Meat", category: "Meat", location: "Fridge", daysSealed: 5, daysAfterOpening: 2 },
  { name: "Deli Ham", category: "Meat", location: "Fridge", daysSealed: 7, daysAfterOpening: 5 },
  { name: "Deli Turkey", category: "Meat", location: "Fridge", daysSealed: 7, daysAfterOpening: 5 },
  { name: "Ground Beef", category: "Meat", location: "Freezer", daysSealed: 120, daysAfterOpening: 2 },
  { name: "Ground Pork", category: "Meat", location: "Freezer", daysSealed: 120, daysAfterOpening: 2 },
  { name: "Ground Turkey", category: "Meat", location: "Freezer", daysSealed: 120, daysAfterOpening: 2 },
  { name: "Halibut", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 2 },
  { name: "Ham", category: "Meat", location: "Fridge", daysSealed: 7, daysAfterOpening: 5 },
  { name: "Hot Dogs", category: "Meat", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Italian Sausage", category: "Meat", location: "Fridge", daysSealed: 7, daysAfterOpening: 3 },
  { name: "Lamb Chops", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 3 },
  { name: "Lobster", category: "Meat", location: "Fridge", daysSealed: 2, daysAfterOpening: 1 },
  { name: "Mahi Mahi", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 2 },
  { name: "Pepperoni", category: "Meat", location: "Fridge", daysSealed: 42, daysAfterOpening: 21 },
  { name: "Pork Chops", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 3 },
  { name: "Pork Tenderloin", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 3 },
  { name: "Prosciutto", category: "Meat", location: "Fridge", daysSealed: 14, daysAfterOpening: 5 },
  { name: "Ribeye Steak", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 3 },
  { name: "Rotisserie Chicken", category: "Meat", location: "Fridge", daysSealed: 4, daysAfterOpening: 3 },
  { name: "Salami", category: "Meat", location: "Fridge", daysSealed: 42, daysAfterOpening: 14 },
  { name: "Salmon", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 2 },
  { name: "Scallops", category: "Meat", location: "Freezer", daysSealed: 90, daysAfterOpening: 1 },
  { name: "Shrimp", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 2 },
  { name: "Sirloin Steak", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 3 },
  { name: "Smoked Salmon", category: "Meat", location: "Fridge", daysSealed: 14, daysAfterOpening: 5 },
  { name: "Swordfish", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 2 },
  { name: "Tilapia", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 2 },
  { name: "Tuna", category: "Meat", location: "Pantry", daysSealed: 730, daysAfterOpening: 3 },
  { name: "Tuna Steak", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 1 },
  { name: "Turkey Breast", category: "Meat", location: "Freezer", daysSealed: 180, daysAfterOpening: 3 },

  // === CONDIMENTS & SAUCES ===
  { name: "BBQ Sauce", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 120 },
  { name: "Buffalo Sauce", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Chili Garlic Sauce", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Dijon Mustard", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 365 },
  { name: "Fish Sauce", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Hoisin Sauce", category: "Pantry", location: "Fridge", daysSealed: 540, daysAfterOpening: 90 },
  { name: "Honey Mustard", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 60 },
  { name: "Horseradish", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Hot Sauce", category: "Pantry", location: "Fridge", daysSealed: 730, daysAfterOpening: 180 },
  { name: "Hummus", category: "Pantry", location: "Fridge", daysSealed: 30, daysAfterOpening: 7 },
  { name: "Ketchup", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Marinara Sauce", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 7 },
  { name: "Mayonnaise", category: "Pantry", location: "Fridge", daysSealed: 180, daysAfterOpening: 60 },
  { name: "Mustard", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 365 },
  { name: "Oyster Sauce", category: "Pantry", location: "Fridge", daysSealed: 540, daysAfterOpening: 90 },
  { name: "Pesto", category: "Pantry", location: "Fridge", daysSealed: 180, daysAfterOpening: 7 },
  { name: "Pickle Relish", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Ranch Dressing", category: "Pantry", location: "Fridge", daysSealed: 180, daysAfterOpening: 30 },
  { name: "Salsa", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 14 },
  { name: "Soy Sauce", category: "Pantry", location: "Pantry", daysSealed: 1095, daysAfterOpening: 365 },
  { name: "Sriracha", category: "Pantry", location: "Fridge", daysSealed: 730, daysAfterOpening: 180 },
  { name: "Steak Sauce", category: "Pantry", location: "Fridge", daysSealed: 540, daysAfterOpening: 90 },
  { name: "Tahini", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Tartar Sauce", category: "Pantry", location: "Fridge", daysSealed: 180, daysAfterOpening: 60 },
  { name: "Teriyaki Sauce", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 30 },
  { name: "Vinaigrette", category: "Pantry", location: "Fridge", daysSealed: 90, daysAfterOpening: 14 },
  { name: "Worcestershire Sauce", category: "Pantry", location: "Pantry", daysSealed: 1095, daysAfterOpening: 365 },
  { name: "Yellow Mustard", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 365 },

  // === PANTRY STAPLES ===
  { name: "All-Purpose Flour", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Almond Butter", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Almond Flour", category: "Pantry", location: "Pantry", daysSealed: 180, daysAfterOpening: 90 },
  { name: "Baking Powder", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Baking Soda", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 180 },
  { name: "Balsamic Vinegar", category: "Pantry", location: "Pantry", daysSealed: 1095, daysAfterOpening: 365 },
  { name: "Black Beans", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 5 },
  { name: "Bread", category: "Pantry", location: "Pantry", daysSealed: 7, daysAfterOpening: 5 },
  { name: "Bread Crumbs", category: "Pantry", location: "Pantry", daysSealed: 180, daysAfterOpening: 90 },
  { name: "Brown Rice", category: "Pantry", location: "Pantry", daysSealed: 180, daysAfterOpening: 90 },
  { name: "Brown Sugar", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 120 },
  { name: "Canola Oil", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Capers", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 365 },
  { name: "Chicken Broth", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 5 },
  { name: "Chickpeas", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 5 },
  { name: "Cocoa Powder", category: "Pantry", location: "Pantry", daysSealed: 1095, daysAfterOpening: 365 },
  { name: "Coconut Milk", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 5 },
  { name: "Coconut Oil", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Cornstarch", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Couscous", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Crackers", category: "Pantry", location: "Pantry", daysSealed: 180, daysAfterOpening: 14 },
  { name: "Dried Pasta", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Granola", category: "Pantry", location: "Pantry", daysSealed: 180, daysAfterOpening: 30 },
  { name: "Honey", category: "Pantry", location: "Pantry", daysSealed: 1095, daysAfterOpening: 1095 },
  { name: "Jam", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 30 },
  { name: "Jelly", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 30 },
  { name: "Kidney Beans", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 5 },
  { name: "Lentils", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 365 },
  { name: "Maple Syrup", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Oats", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Olive Oil", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 180 },
  { name: "Olives", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 14 },
  { name: "Panko", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Pasta", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Peanut Butter", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Pickles", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Popcorn Kernels", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Quinoa", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Raisins", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 90 },
  { name: "Rice", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "Sesame Oil", category: "Pantry", location: "Pantry", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Sugar", category: "Pantry", location: "Pantry", daysSealed: 1095, daysAfterOpening: 730 },
  { name: "Sun-Dried Tomatoes", category: "Pantry", location: "Fridge", daysSealed: 365, daysAfterOpening: 14 },
  { name: "Tomato Paste", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 7 },
  { name: "Tomato Sauce", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 7 },
  { name: "Tortillas", category: "Pantry", location: "Pantry", daysSealed: 21, daysAfterOpening: 7 },
  { name: "Vegetable Broth", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 5 },
  { name: "Walnuts", category: "Pantry", location: "Pantry", daysSealed: 180, daysAfterOpening: 90 },
  { name: "White Rice", category: "Pantry", location: "Pantry", daysSealed: 730, daysAfterOpening: 365 },
  { name: "White Wine Vinegar", category: "Pantry", location: "Pantry", daysSealed: 1095, daysAfterOpening: 365 },

  // === FROZEN ===
  { name: "Frozen Berries", category: "Other", location: "Freezer", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Frozen Broccoli", category: "Other", location: "Freezer", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Frozen Corn", category: "Other", location: "Freezer", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Frozen Pizza", category: "Other", location: "Freezer", daysSealed: 180, daysAfterOpening: null },
  { name: "Frozen Spinach", category: "Other", location: "Freezer", daysSealed: 365, daysAfterOpening: 180 },
  { name: "Frozen Waffles", category: "Other", location: "Freezer", daysSealed: 240, daysAfterOpening: 60 },
  { name: "Ice Cream", category: "Other", location: "Freezer", daysSealed: 60, daysAfterOpening: 30 },

  // === BEVERAGES ===
  { name: "Almond Milk", category: "Other", location: "Fridge", daysSealed: 10, daysAfterOpening: 7 },
  { name: "Apple Juice", category: "Other", location: "Fridge", daysSealed: 21, daysAfterOpening: 7 },
  { name: "Coconut Water", category: "Other", location: "Pantry", daysSealed: 365, daysAfterOpening: 3 },
  { name: "Orange Juice", category: "Other", location: "Fridge", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Soy Milk", category: "Other", location: "Fridge", daysSealed: 10, daysAfterOpening: 7 },

  // === BAKERY ===
  { name: "Bagels", category: "Other", location: "Pantry", daysSealed: 5, daysAfterOpening: 3 },
  { name: "Croissants", category: "Other", location: "Pantry", daysSealed: 3, daysAfterOpening: 2 },
  { name: "English Muffins", category: "Other", location: "Pantry", daysSealed: 14, daysAfterOpening: 7 },
  { name: "Hamburger Buns", category: "Other", location: "Pantry", daysSealed: 7, daysAfterOpening: 5 },
  { name: "Hot Dog Buns", category: "Other", location: "Pantry", daysSealed: 7, daysAfterOpening: 5 },
  { name: "Pita Bread", category: "Other", location: "Pantry", daysSealed: 7, daysAfterOpening: 5 },
  { name: "Sandwich Bread", category: "Other", location: "Pantry", daysSealed: 7, daysAfterOpening: 5 },
  { name: "Sourdough", category: "Other", location: "Pantry", daysSealed: 5, daysAfterOpening: 3 },
  { name: "Wraps", category: "Other", location: "Pantry", daysSealed: 14, daysAfterOpening: 7 },
];

