/** Fun facts shown while AI scans / loads (EN + ES). */
export const FOOD_FACTS = [
  { en: "Honey never spoils — archaeologists have found edible honey in ancient tombs.", es: "La miel no se echa a perder — se ha encontrado miel comestible en tumbas antiguas." },
  { en: "Bananas ripen faster when stored next to other fruit.", es: "Los plátanos maduran más rápido junto a otras frutas." },
  { en: "Refrigerating bread actually makes it go stale faster — freeze it instead.", es: "Refrigerar el pan lo reseca más rápido — mejor congélalo." },
  { en: "Apples float because about 25% of their volume is air.", es: "Las manzanas flotan porque cerca del 25% de su volumen es aire." },
  { en: "Carrots were originally purple, not orange.", es: "Las zanahorias eran moradas originalmente, no naranjas." },
  { en: "Tomatoes are botanically a fruit, not a vegetable.", es: "Los tomates son fruta botánicamente, no verdura." },
  { en: "Peanuts aren't nuts — they're legumes, like beans.", es: "El maní no es nuez — es legumbre, como los frijoles." },
  { en: "Lettuce is mostly water — about 96%.", es: "La lechuga es casi agua — alrededor del 96%." },
  { en: "Freezing food pauses bacteria — it doesn't kill them.", es: "Congelar pausa las bacterias — no las mata." },
  { en: "Opened ketchup lasts months in the fridge, not forever on the door.", es: "El ketchup abierto dura meses en el refrigerador, no para siempre en la puerta." },
  { en: "The \"sell by\" date is for stores — \"use by\" is for you.", es: "La fecha de venta es para tiendas — \"consumir antes\" es para ti." },
  { en: "Cooked rice left at room temperature can be risky after 2 hours.", es: "El arroz cocido a temperatura ambiente puede ser riesgoso después de 2 horas." },
  { en: "Avocados ripen best on the counter, then move to the fridge.", es: "Los aguacates maduran mejor en la encimera; luego al refrigerador." },
  { en: "Potatoes and onions should be stored apart — each speeds the other's spoilage.", es: "Papas y cebollas deben guardarse separadas — se aceleran el deterioro." },
  { en: "Eggs stay fresher longer in the coldest part of the fridge, not the door.", es: "Los huevos duran más en la parte más fría del refrigerador, no en la puerta." },
  { en: "Smell and sight matter as much as the date on the package.", es: "El olor y la vista importan tanto como la fecha del paquete." },
  { en: "Washing berries right before eating helps them last longer.", es: "Lavar las bayas justo antes de comerlas ayuda a que duren más." },
  { en: "Hard cheese lasts longer than soft cheese after opening.", es: "El queso duro dura más que el blando después de abrirlo." },
  { en: "Your nose is one of the best tools for spotting spoiled food.", es: "Tu nariz es una de las mejores herramientas para detectar comida en mal estado." },
  { en: "Tracking what you have is the easiest way to waste less food.", es: "Rastrear lo que tienes es la forma más fácil de desperdiciar menos comida." },
  { en: "Milk stays fresher on a fridge shelf — the door is the warmest spot.", es: "La leche dura más en un estante del refrigerador — la puerta es la zona más cálida." },
  { en: "Store mushrooms in a paper bag — plastic traps moisture and speeds spoilage.", es: "Guarda los hongos en bolsa de papel — el plástico atrapa humedad y acelera el deterioro." },
  { en: "Defrost meat in the fridge overnight — never on the counter.", es: "Descongela la carne en el refrigerador de la noche a la mañana — nunca en la encimera." },
  { en: "Brown bananas are sweeter — perfect for smoothies and banana bread.", es: "Los plátanos marrones son más dulces — perfectos para batidos y pan de plátano." },
  { en: "Leafy greens last longer with a dry paper towel in the bag.", es: "Las verduras de hoja duran más con una toalla de papel seca en la bolsa." },
  { en: "Tomatoes lose flavor in the fridge — ripen on the counter, then chill if needed.", es: "Los tomates pierden sabor en el refrigerador — madúralos en la encimera y enfría solo si hace falta." },
  { en: "Fresh herbs last longer standing in water, like a bouquet.", es: "Las hierbas frescas duran más en agua, como un ramo de flores." },
  { en: "A full freezer runs more efficiently than an empty one.", es: "Un congelador lleno funciona más eficientemente que uno vacío." },
  { en: "First in, first out — use older items before newer ones.", es: "Primero en entrar, primero en salir — usa lo más viejo antes que lo nuevo." },
  { en: "Clear containers help you spot food before it goes bad.", es: "Los recipientes transparentes te ayudan a ver la comida antes de que se eche a perder." },
  { en: "Cooked chicken keeps about 3–4 days in the fridge.", es: "El pollo cocido dura unos 3–4 días en el refrigerador." },
  { en: "Fresh fish is best used within 1–2 days of buying.", es: "El pescado fresco es mejor usarlo en 1–2 días después de comprarlo." },
  { en: "Deli meat is safest within 3–5 days after opening.", es: "La carne de deli es más segura dentro de 3–5 días después de abrir." },
  { en: "Nuts go rancid in the pantry — the fridge keeps them fresh longer.", es: "Las nueces se ponen rancias en la despensa — el refrigerador las mantiene frescas más tiempo." },
  { en: "Broccoli lasts longer unwashed in the crisper drawer.", es: "El brócoli dura más sin lavar en el cajón de verduras." },
  { en: "Basil wilts in the cold — store it at room temperature in water.", es: "La albahaca se marchita con el frío — guárdala a temperatura ambiente en agua." },
  { en: "Watermelon doesn't ripen after it's picked — choose a ripe one at the store.", es: "La sandía no madura después de cosecharla — elige una madura en la tienda." },
  { en: "Hard cheese keeps best wrapped in wax paper, not tight plastic.", es: "El queso duro se conserva mejor en papel encerado, no en plástico apretado." },
  { en: "Opened salsa usually lasts about 2 weeks in the fridge.", es: "La salsa abierta suele durar unas 2 semanas en el refrigerador." },
  { en: "Citrus fruit lasts much longer refrigerated than on the counter.", es: "Los cítricos duran mucho más refrigerados que en la encimera." },
  { en: "Garlic and whole onions belong in a cool, dry pantry — not the fridge.", es: "El ajo y las cebollas enteras van en una despensa fresca y seca — no en el refrigerador." },
  { en: "Label leftovers with the date — your future self will thank you.", es: "Etiqueta las sobras con la fecha — tu yo del futuro te lo agradecerá." },
  { en: "Meal planning is one of the best ways to cut food waste.", es: "Planificar comidas es una de las mejores formas de reducir el desperdicio." },
  { en: "Strawberries are the only fruit with seeds on the outside.", es: "Las fresas son la única fruta con semillas por fuera." },
  { en: "Spinach wilts fast — plan to use it within a few days.", es: "La espinaca se marchita rápido — planea usarla en pocos días." },
  { en: "Olive oil lasts longer away from heat and direct light.", es: "El aceite de oliva dura más lejos del calor y la luz directa." },
  { en: "Dry pasta keeps for years — opened packages about a year.", es: "La pasta seca dura años — los paquetes abiertos, alrededor de un año." },
  { en: "Coffee stays fresher in an airtight container away from sunlight.", es: "El café se mantiene más fresco en un recipiente hermético lejos del sol." },
  { en: "Americans throw away roughly 30% of the food they buy.", es: "Los estadounidenses tiran aproximadamente el 30% de la comida que compran." },
  { en: "Leftovers make great lunches — track them so they don't get forgotten.", es: "Las sobras son excelentes almuerzos — rastréalas para no olvidarlas." },
  { en: "Never refreeze raw meat that thawed on the counter.", es: "Nunca vuelvas a congelar carne cruda descongelada en la encimera." },
  { en: "Canned goods often last years past the date if the can isn't damaged.", es: "Los enlatados suelen durar años después de la fecha si la lata no está dañada." },
  { en: "Washing all produce right when you get home can shorten shelf life.", es: "Lavar toda la fruta y verdura al llegar a casa puede acortar su vida útil." },
  { en: "A ripe avocado gives slightly when you gently squeeze it.", es: "Un aguacate maduro cede ligeramente al apretarlo suavemente." },
  { en: "Keeping a running list of what's in your fridge cuts duplicate buys.", es: "Llevar una lista de lo que hay en tu refrigerador evita compras duplicadas." },
];
