export const TUTORIALS = {
  home: [
    { emoji: "🥦", title: "Welcome to TrackFresh!", body: "Save Money. Waste Less. Eat Better. TrackFresh tracks food, shows what expires soon, suggests recipes, plans meals, and builds your shopping list. Everything saves on your device." },
    { emoji: "🍽️", title: "Your Kitchen Today", body: "Your Kitchen Today shows what's urgent — Past Date, Expires today, or days left. When everything looks good, you'll see Everything looks good today. Tap See All › to open Organize your kitchen." },
    { emoji: "📂", title: "Mark What You've Opened", body: "Tap Mark What You've Opened on the dashboard or in Tracker. TrackFresh sets a new use-by countdown based on shelf life after opening." },
    { emoji: "🧭", title: "Explore From Home", body: "Home links to Tracker, Recipes, Shopping List, Meals, Stores, FDA / USDA, Partners, Search & Save, and Suggestions — tap any tile to jump in." },
  ],
  tracker: [
    { emoji: "🧾", title: "Snap a receipt — Start Here", body: "Fastest way: snap your grocery receipt. Tap Snap a receipt on Tracker. Fastest — reads all your items. Take or upload one photo — AI adds everything for you." },
    { emoji: "📷", title: "Snap items with camera", body: "No receipt? Barcodes & labels. Tap Snap items with camera to photograph products. AI identifies each item, category, Fridge/Freezer/Pantry, and storage tips." },
    { emoji: "✏️", title: "Type it in", body: "Tap Type it in for quick add with AI autocomplete — no photo needed." },
    { emoji: "📂", title: "Mark What You've Opened", body: "Tap Mark What You've Opened to mark an existing item as opened. Search by name, use voice, or browse by Fridge/Freezer/Pantry." },
    { emoji: "🗂️", title: "Organize your kitchen", body: "Set where each item lives and when to use it. All view shows Fridge, Freezer, and Pantry columns. Tap ▼ on any item for details. Use the 📅 calendar to set dates. Past date means it's overdue." },
    { emoji: "⏰", title: "Watch the badges", body: "Past date, Use soon, and Need exp. date badges tell you what needs attention. Color glows on each row show urgency at a glance." },
    { emoji: "🎤", title: "Speak or tap the calendar", body: "Tap 🎤 to speak the date, or use the calendar. After a scan, set dates hands-free or tap 📅 on any item in Organize your kitchen." },
  ],
  recipes: [
    { emoji: "🍳", title: "Get recipe ideas", body: "Matched to what's in your fridge, pantry & freezer. Tap for suggested recipes from 'my kitchen' — starting with what expires soonest." },
    { emoji: "❤️", title: "Recipe ideas & Favorites", body: "Switch between Recipe ideas and Favorites. Tap ❤️ to save a recipe. Saved to favorites keeps it for later." },
    { emoji: "🛒", title: "Add missing ingredients", body: "Tap + on any missing ingredient to add it to your Shopping List. Items you already have are marked ✓." },
    { emoji: "🔒", title: "Dietary filters active", body: "Every recipe respects restrictions in Dietary Needs — for the whole household and each family member." },
  ],
  shopping: [
    { emoji: "🛒", title: "Shopping List", body: "Add items yourself — or look for ones we add when you mark food Used, or when it's expiring at home. Check off items as you shop." },
    { emoji: "⏱️", title: "Expiring at home", body: "Day badges = expiring at home. Check to add a replacement." },
    { emoji: "🚚", title: "Order groceries online", body: "Pick Instacart, Walmart, or Amazon Fresh on your list — Order groceries online in one tap." },
    { emoji: "🔄", title: "Used up — restock", body: "When you mark a tracked item as Used, it can appear on your list with a Used up badge as a restock reminder." },
    { emoji: "⚠️", title: "Allergen warnings", body: "Shopping items that match your dietary restrictions are flagged with a red ⚠️ badge automatically." },
  ],
  meals: [
    { emoji: "📅", title: "Meal Planner", body: "Monday through Sunday — Breakfast, Lunch, and Dinner. Each slot shows the meal name. Tap ▼ to view ingredients and instructions." },
    { emoji: "🤖", title: "Plan My Week", body: "Tap Plan My Week and TrackFresh fills all 21 meals using your tracked food, prioritizing items expiring soonest. Every meal respects dietary restrictions." },
    { emoji: "✏️", title: "Edit any meal", body: "Tap ✕ on any slot to clear it, then tap the slot to pick a different meal. Add custom names or search the built-in list." },
    { emoji: "➕", title: "+ Add meal", body: "Tap + Add meal on any empty slot to search meals or add a custom name." },
  ],
  community: [
    { emoji: "👥", title: "Community Chat", body: "Connect with other TrackFresh users. Share what you cooked, ask food questions, and cheer each other on." },
    { emoji: "🤖", title: "Ask AI by Text", body: "Type a food question and tap Ask AI Text — TrackFresh AI answers in the chat." },
    { emoji: "🎤", title: "Ask AI by Voice", body: "Tap 🎤 Ask AI to speak your question — transcribed and sent to AI automatically." },
    { emoji: "💡", title: "Recipes & Tips tabs", body: "Share a recipe in the Recipes tab or post a tip in the Tips tab to help others waste less." },
  ],
  more: [
    { emoji: "💬", title: "Your Ideas Matter", body: "We're a small team with a big mission. Leave a suggestion, vote what we build next, and use Save & Restore Backup — your feedback shapes TrackFresh." },
    { emoji: "💰", title: "Search & Save", body: "Take your TrackFresh app to a participating store. Present it at checkout and show the expiry date — 20% off at participating stores." },
    { emoji: "🤝", title: "Partners", body: "The ecosystem for less waste. One platform. One goal: waste less, eat better. Shoppers, Supermarkets, and Brands." },
    { emoji: "🌐", title: "English / Spanish", body: "Switch between English and Español with one tap. Every label, button, and tip updates instantly." },
    { emoji: "💾", title: "Save & Restore Backup", body: "Move your kitchen between phone and PC. Export a backup file, then Restore from Backup on your other device." },
  ],
  "stores-page": [
    { emoji: "🏪", title: "Shop Online", body: "Tap any store to shop for groceries online — Amazon Fresh, Kroger, Walmart, Whole Foods, and more." },
    { emoji: "🚚", title: "Order groceries online", body: "On Shopping List, pick Instacart, Walmart, or Amazon Fresh to open delivery in one tap." },
    { emoji: "💰", title: "Search & Save in store", body: "For checkout savings in person, open Search & Save — show your discount card and the product expiry date." },
  ],
  dietary: [
    { emoji: "🥗", title: "Household restrictions", body: "Set restrictions for everyone — vegetarian, vegan, gluten-free, keto, nut-free, dairy-free, and more. These filter every recipe and meal plan." },
    { emoji: "👨‍👩‍👧", title: "Family member profiles", body: "Add a name for each household member and set their individual restrictions. The app merges everyone's needs." },
    { emoji: "⚠️", title: "Allergen alerts in Shopping", body: "Shopping list items that match any active restriction are flagged with a red ⚠️ badge automatically." },
    { emoji: "🎯", title: "Active across the app", body: "Dietary profiles are live in Recipes, Shopping allergen warnings, and the Meal Planner." },
  ],
  partners: [
    { emoji: "🤝", title: "The ecosystem for less waste", body: "TrackFresh connects home cooks, grocery retailers, and food brands — building a smarter, less wasteful food system together." },
    { emoji: "🏪", title: "Supermarkets", body: "Meet shoppers where they already plan meals and track what's in their kitchen. Search & Save helps move near-expiry product before it goes to waste." },
    { emoji: "🏷️", title: "Brands", body: "Food brands reach motivated home cooks through meal planner placements — with privacy built in. Brands pay you to introduce new products." },
    { emoji: "🔒", title: "Customer data stays private. Always.", body: "Partners see redemption counts — not names or contact details. Supermarkets own their customer relationships." },
  ],
  "search-save": [
    { emoji: "💰", title: "Search & Save", body: "When an item expires within 2 days, TrackFresh helps you save — and helps the store sell it before it goes to waste." },
    { emoji: "🏷️", title: "Your discounts", body: "Track items expiring within 2 days to unlock your Search and Save discount card. Tap any card for checkout details." },
    { emoji: "🛒", title: "At checkout", body: "Take your TrackFresh app with you to a participating store. Present this at checkout and show the expiry date of the product." },
    { emoji: "🤝", title: "Everyone wins", body: "Shoppers save 20% off. Stores sell through before expiry. TrackFresh helps both sides waste less." },
  ],
  suggestions: [
    { emoji: "💬", title: "Your Ideas Matter", body: "We're a small team with a big mission. Your feedback shapes what we build next." },
    { emoji: "✍️", title: "Leave a suggestion", body: "Pick a category, write your idea, and tap Send Suggestion. We read every one." },
    { emoji: "🗳️", title: "Vote what we build next", body: "Tap 👍 once for your top pick — expiry alerts, family kitchen, dinner vote, auto grocery list, weekly savings report, or nearby store deals." },
    { emoji: "📲", title: "Save & Restore Backup", body: "Move your kitchen between phone and PC. Tap Save Backup, then Restore from Backup on your other device." },
  ],
};

export const TOUR_SLIDES = [
  {
    titleEn: "Welcome to TrackFresh.",
    titleEs: "Bienvenido a TrackFresh.",
    bodyEn: "Save Money. Waste Less. Eat Better.",
    bodyEs: "Ahorra Dinero. Menos Desperdicio. Mejor Cocina.",
    visual: { type: "emoji", value: "🌿" },
  },
  {
    window: { icon: "🥦", en: "Tracker", es: "Rastreador" },
    titleEn: "Snap a receipt.",
    titleEs: "Foto del recibo.",
    bodyEn: "Fastest way: snap your grocery receipt. Tap Snap a receipt. Take or upload one photo — AI adds everything for you.",
    bodyEs: "Lo más rápido: foto de tu recibo de compra. Toca Foto del recibo. Toma o sube una foto — la IA agrega todo.",
    visual: { type: "img", src: "/tour-receipt.png" },
  },
  {
    window: { icon: "🥦", en: "Tracker", es: "Rastreador" },
    titleEn: "Snap items with camera.",
    titleEs: "Foto de productos.",
    bodyEn: "No receipt? Barcodes & labels. Tap Snap items with camera — AI identifies each product.",
    bodyEs: "¿Sin recibo? Códigos y etiquetas. Toca Foto de productos — la IA identifica cada artículo.",
    visual: { type: "img", src: "/tour-groceries.jpeg" },
  },
  {
    window: { icon: "🥦", en: "Tracker", es: "Rastreador" },
    titleEn: "Speak the date.",
    titleEs: "Di la fecha.",
    bodyEn: "Tap 🎤 to speak the date, or use the calendar.",
    bodyEs: "Toca 🎤 para decir la fecha, o usa el calendario.",
    visual: { type: "emoji", value: "🎤" },
  },
  {
    window: { icon: "🥦", en: "Tracker", es: "Rastreador" },
    titleEn: "Choose how to add items.",
    titleEs: "Elige cómo agregar.",
    bodyEn: "Snap a receipt, Snap items with camera, or Type it in — three ways to build your kitchen.",
    bodyEs: "Foto del recibo, Foto de productos o Escribir a mano — tres formas de llenar tu cocina.",
    visual: { type: "emoji", value: "🏷️" },
  },
  {
    window: { icon: "🥦", en: "Tracker", es: "Rastreador" },
    titleEn: "Organize your kitchen.",
    titleEs: "Organiza tu cocina.",
    bodyEn: "Set where each item lives and when to use it. All view shows Fridge, Freezer, and Pantry columns. Tap ▼ on any item for details. Past date means it's overdue.",
    bodyEs: "Indica dónde va cada artículo y cuándo usarlo. La vista Todo muestra nevera, congelador y despensa. Toca ▼ para detalles. Fecha pasada = vencido.",
    visual: { type: "emoji", value: "📦" },
  },
  {
    window: { icon: "🍽️", en: "Home", es: "Inicio" },
    titleEn: "Your Kitchen Today.",
    titleEs: "Tu Cocina Hoy.",
    bodyEn: "See what's urgent — Past Date, Expires today, or days left. Tap See All › to open Organize your kitchen.",
    bodyEs: "Ve lo urgente — Fecha pasada, Vence hoy o días restantes. Toca Ver Todo › para Organiza tu cocina.",
    visual: { type: "emoji", value: "⏰" },
  },
  {
    window: { icon: "🍳", en: "Recipes", es: "Recetas" },
    titleEn: "Get recipe ideas.",
    titleEs: "Obtener ideas de recetas.",
    bodyEn: "Matched to what's in your fridge, pantry & freezer. Tap for suggested recipes from 'my kitchen'.",
    bodyEs: "Basado en lo que tienes en tu refrigerador, despensa y congelador. Toca para recetas sugeridas de 'mi cocina'.",
    visual: { type: "emoji", value: "🍳" },
  },
  {
    window: { icon: "🍳", en: "Recipes", es: "Recetas" },
    titleEn: "Recipe ideas & Favorites.",
    titleEs: "Ideas de recetas y Favoritos.",
    bodyEn: "Switch between Recipe ideas and Favorites. Tap ❤️ to save. Tap + on missing ingredients for your Shopping List.",
    bodyEs: "Cambia entre Ideas de recetas y Favoritos. Toca ❤️ para guardar. Toca + en ingredientes faltantes para tu lista.",
    visual: { type: "emoji", value: "❤️" },
  },
  {
    window: { icon: "🛒", en: "Shopping List", es: "Lista de Compras" },
    titleEn: "Shopping List.",
    titleEs: "Lista de Compras.",
    bodyEn: "Add items yourself — or look for ones we add when you mark food Used, or when it's expiring at home. Order groceries online with Instacart, Walmart, or Amazon Fresh.",
    bodyEs: "Agrega artículos tú — o busca los que agregamos cuando marcas comida Usada o está por vencer. Pide en línea con Instacart, Walmart o Amazon Fresh.",
    visual: { type: "emoji", value: "🛒" },
  },
  {
    window: { icon: "🏪", en: "Stores", es: "Tiendas" },
    titleEn: "Shop Online.",
    titleEs: "Comprar en Línea.",
    bodyEn: "Tap any store to shop for groceries online.",
    bodyEs: "Toca cualquier tienda para comprar alimentos.",
    visual: { type: "emoji", value: "🏪" },
  },
  {
    window: { icon: "💰", en: "Search & Save", es: "Buscar y Ahorrar" },
    titleEn: "Everyone wins.",
    titleEs: "Todos ganan.",
    bodyEn: "Take your TrackFresh app to a participating store. Present this at checkout and show the expiry date of the product. 20% off.",
    bodyEs: "Lleva tu app TrackFresh a una tienda participante. Preséntala en caja y muestra la fecha de vencimiento. 20% de descuento.",
    visual: { type: "emoji", value: "💰" },
  },
  {
    window: { icon: "🤝", en: "Partners", es: "Socios" },
    titleEn: "The ecosystem for less waste.",
    titleEs: "El ecosistema para desperdiciar menos.",
    bodyEn: "One platform. One goal: waste less, eat better. Shoppers, Supermarkets, and Brands.",
    bodyEs: "Una plataforma. Un objetivo: desperdiciar menos, comer mejor. Compradores, Supermercados y Marcas.",
    visual: { type: "emoji", value: "🤝" },
  },
  {
    window: { icon: "📅", en: "Meals", es: "Comidas" },
    titleEn: "Plan My Week.",
    titleEs: "Planificar Mi Semana.",
    bodyEn: "Fill Breakfast, Lunch, and Dinner for the whole week — manually or tap Plan My Week with what you already have.",
    bodyEs: "Llena desayuno, almuerzo y cena toda la semana — manualmente o toca Planificar Mi Semana con lo que ya tienes.",
    visual: { type: "emoji", value: "📅" },
  },
  {
    window: { icon: "🚨", en: "FDA / USDA", es: "FDA / USDA" },
    titleEn: "FDA / USDA.",
    titleEs: "FDA / USDA.",
    bodyEn: "Food safety alerts & tips — real-time recall alerts, storage guides, and department tips in the app.",
    bodyEs: "Alertas y consejos de seguridad — retiros en tiempo real, guías de almacenamiento y consejos por departamento.",
    visual: { type: "emoji", value: "🚨" },
  },
  {
    window: { icon: "🌐", en: "Language", es: "Idioma" },
    titleEn: "English. Español.",
    titleEs: "Inglés. Español.",
    bodyEn: "Tap the flag in the header — switch anytime.",
    bodyEs: "Toca la bandera en la cabecera — cambia cuando quieras.",
    visual: { type: "emoji", value: "🌐" },
  },
  {
    window: { icon: "💬", en: "Suggestions", es: "Sugerencias" },
    titleEn: "Your Ideas Matter.",
    titleEs: "Tus Ideas Importan.",
    bodyEn: "We're a small team with a big mission. Leave a suggestion, vote what we build next, and Save & Restore Backup — your feedback shapes TrackFresh.",
    bodyEs: "Somos un equipo pequeño con una gran misión. Deja una sugerencia, vota lo que construimos y Guardar y Restaurar Respaldo — tu opinión forma TrackFresh.",
    visual: { type: "img", src: "/tour-feedback.jpg" },
  },
  {
    titleEn: "Ready?",
    titleEs: "¿Listo?",
    bodyEn: "Tap the tiles on Home to begin.",
    bodyEs: "Toca los iconos en Inicio para comenzar.",
    visual: { type: "emoji", value: "🚀" },
  },
];
